### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)

### ISSUE THREAD

**Issue by nitsharm1910** [pallets/markupsafe#284]
With the new release getting the below error. It is working fine with version= 2.0.1

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by heavelock** [comment]
From the changelog https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0 
```
Remove soft_unicode, which was previously deprecated. Use soft_str instead. [#261](https://github.com/pallets/markupsafe/pull/261)
```

But why the doing a breaking change in a minor version?!

**Comment by sc-laurence** [comment]
I am using python:3.7 image and experiencing the same error, can someone suggest  a work around for now, that would be much appreciated!

**Comment by stefanweiser** [comment]
I'm using conan in python 3.7 up to 3.10 and this issue breaks conan. Please stick to semantic versioning and don't make breaking changes in minor version updates!

**Comment by Lebski** [comment]
> 2.0.1



> I am using python:3.7 and flask 1.1.3 and experiencing the same error, can someone suggest a work around for now, that would be much appreciated!

Set the version to `2.0.1` in your requirements.txt or install it with `python -m pip install markupsafe==2.0.1`

**Comment by vaibhavsharma271** [comment]
worked for me after markupsafe==2.0.1 in  requirements.txt

**Comment by davidism** [comment]
You are using an unsupported version of the project, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by jasal82** [comment]
Removing deprecated functions nevertheless requires a major release. Semantic versioning won't save us, but we don't have to artificially worsen the situation by not following the basic rules.

**Comment by MiltiadisKoutsokeras** [comment]
This error surfaces on Python 3.7.12, Flask 1.1.4 and MarkupSafe 2.0.1. So it is not resolved.

**Comment by ThiefMaster** [comment]
Did you read the comments? You need to pin your dependencies or update to the latest Jinja version.

**Comment by varun379** [comment]
I am getting the same error even though I have the latest Jinja2 and MarkUpSafe==2.0.1:

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)

What can I do to fix this. I am trying to run an airflow pipeline. Full error log below: 

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 42, in <module>
    from airflow.models import DAG
  File "/usr/local/lib/python3.7/site-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 36, in <module>
    import jinja2
  File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python3.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python3.7/site-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
